#include<iostream.h>
#include<conio.h>
void main()
{
 char a;
 cout<<"Enter a color\n"<<"VIBGYOR"<<endl;
 cin>>a;
 if(a=='V')
 cout<<"Violet\n";
 else if(a=='I')
 cout<<"Indigo\n";
 else if(a=='B')
 cout<<"Blue\n";
  else if(a=='G')
 cout<<"Green\n";
  else if(a=='O')
 cout<<"Orange\n";
  else if(a=='Y')
 cout<<"Yellow\n";
  else if(a=='R')
 cout<<"Red\n";
  else
 cout<<"Not my color\n";
 getch();
}